public_homepage:
    pattern:  /
    defaults: { _controller: PublicBundle:Default:index }

# public_description:
#     pattern:  /description
#     defaults: { _controller: PublicBundle:Default:description }
